# Generated by Django 4.1.6 on 2023-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillID', models.IntegerField(primary_key=True, serialize=False)),
                ('skillName', models.CharField(max_length=100)),
                ('skillExp', models.IntegerField(max_length=2)),
            ],
        ),
    ]
