# Generated by Django 4.1.6 on 2023-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='onSite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skillExp',
            field=models.IntegerField(),
        ),
    ]
